# disable python warnings if they annoy you
ignore_warnings: false

# ask user for tags if none are provided in the config
enforce_tags: true

# pretty print config tree at the start of the run using Rich library
print_config: true

# Huggingface API of CLIPSeg for pretrained model and tokenizer
clipseg_hf_api: CIDAS/clipseg-rd64-refined