_target_: src.datamodules.BaseDataModule
train_dataset:
  _target_: src.datamodules.datasets.ImageTextMaskDataset
  tokenizer_type: ${tokenizer_type}
  prompt_type: ${prompt_type}
  images_dir: ${data_root}/bkai_polyp/images
  masks_dir: ${data_root}/bkai_polyp/masks
  caps_file: ${data_root}/bkai_polyp/anns/train.json
  img_size: ${img_size}
  zero_prompt: ${zero_prompt}
  img_transforms: ${train_img_transforms}
  mask_transforms: ${train_mask_transforms}

val_dataset:
  _target_: src.datamodules.datasets.ImageTextMaskDataset
  tokenizer_type: ${tokenizer_type}
  prompt_type: ${prompt_type}
  images_dir: ${data_root}/bkai_polyp/images 
  masks_dir: ${data_root}/bkai_polyp/masks
  caps_file: ${data_root}/bkai_polyp/anns/val.json
  img_size: ${img_size}
  context_length: ${context_length}
  img_transforms: ${val_img_transforms}
  mask_transforms: ${val_mask_transforms}

test_dataset:
  _target_: src.datamodules.datasets.ImageTextMaskDataset
  tokenizer_type: ${tokenizer_type}
  prompt_type: ${prompt_type}
  images_dir: ${data_root}/bkai_polyp/images 
  masks_dir: ${data_root}/bkai_polyp/masks
  caps_file: ${data_root}/bkai_polyp/anns/test.json
  img_size: ${img_size}
  context_length: ${context_length}
  img_transforms: ${test_img_transforms}
  mask_transforms: ${test_mask_transforms}

batch_size: 16
num_workers: 4
pin_memory: true