_target_: src.datamodules.BaseDataModule
train_dataset:
  _target_: src.datamodules.datasets.ImageTextMaskDataset
  tokenizer_type: ${tokenizer_type}
  prompt_type: ${prompt_type}
  images_dir: ${data_root}/camus/images/train
  masks_dir: ${data_root}/camus/masks/train
  caps_file: ${data_root}/camus/anns/train.json
  img_size: ${img_size}
  context_length: ${context_length}
  img_transforms: ${train_img_transforms}
  mask_transforms: ${train_mask_transforms}

val_dataset:
  _target_: src.datamodules.datasets.ImageTextMaskDataset
  tokenizer_type: ${tokenizer_type}
  prompt_type: ${prompt_type}
  images_dir: ${data_root}/camus/images/train
  masks_dir: ${data_root}/camus/masks/train
  caps_file: ${data_root}/camus/anns/val.json
  img_size: ${img_size}
  context_length: ${context_length}
  img_transforms: ${val_img_transforms}
  mask_transforms: ${val_mask_transforms}

test_dataset:
  _target_: src.datamodules.datasets.ImageTextMaskDataset
  tokenizer_type: ${tokenizer_type}
  prompt_type: ${prompt_type}
  images_dir: ${data_root}/camus/images/test
  masks_dir: ${data_root}/camus/masks/test
  caps_file: ${data_root}/camus/anns/test.json
  img_size: ${img_size}
  context_length: ${context_length}
  img_transforms: ${test_img_transforms}
  mask_transforms: ${test_mask_transforms}

batch_size: 16
train_val_split: [0.8, 0.2]
num_workers: 4
pin_memory: true